// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/analyze': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analyze.post').default>>>>
    }
    '/api/clients': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/clients').default>>>>
    }
    '/api/clientsByMonth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/clientsByMonth').default>>>>
    }
    '/api/dashboardStats': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboardStats').default>>>>
    }
    '/api/extract/latest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/extract/latest.get').default>>>>
    }
    '/api/extracts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/extracts.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}