// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/8/2025, 4:40:08 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/sunbangheng/Desktop/sitemapAI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI/plugins/**/*.{js,ts,mjs}","/Users/sunbangheng/Desktop/sitemapAI/composables/**/*.{js,ts,mjs}","/Users/sunbangheng/Desktop/sitemapAI/utils/**/*.{js,ts,mjs}","/Users/sunbangheng/Desktop/sitemapAI/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;