// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/2/2025, 3:19:45 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/marvisleung/Documents/Uni/sitemapAI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marvisleung/Documents/Uni/sitemapAI/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marvisleung/Documents/Uni/sitemapAI/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marvisleung/Documents/Uni/sitemapAI/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marvisleung/Documents/Uni/sitemapAI/plugins/**/*.{js,ts,mjs}","/Users/marvisleung/Documents/Uni/sitemapAI/composables/**/*.{js,ts,mjs}","/Users/marvisleung/Documents/Uni/sitemapAI/utils/**/*.{js,ts,mjs}","/Users/marvisleung/Documents/Uni/sitemapAI/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marvisleung/Documents/Uni/sitemapAI/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marvisleung/Documents/Uni/sitemapAI/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marvisleung/Documents/Uni/sitemapAI/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;