// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/6/2025, 1:34:51 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/sunbangheng/Desktop/sitemapAI-full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI-full/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI-full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI-full/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI-full/plugins/**/*.{js,ts,mjs}","/Users/sunbangheng/Desktop/sitemapAI-full/composables/**/*.{js,ts,mjs}","/Users/sunbangheng/Desktop/sitemapAI-full/utils/**/*.{js,ts,mjs}","/Users/sunbangheng/Desktop/sitemapAI-full/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI-full/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI-full/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/sunbangheng/Desktop/sitemapAI-full/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;